// Automatic FlutterFlow imports
import '/backend/schema/structs/index.dart';
import '/flutter_flow/ff_builtin_enums.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import '/app_state.dart';

Future<List<QuestionStruct>> loadScript() async {
  return [
    // ===== M01 - Datos personales =====
    QuestionStruct(
      id: 'm01_intro',
      module: 'M01',
      questionText: 'Empecemos por tus datos personales',
      clarification: 'Unas preguntas básicas para configurar tu declaración.',
      shortHelp: '',
      icon: 'person',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 1,
    ),
    QuestionStruct(
      id: 'm01_civil_status',
      module: 'M01',
      questionText: '¿Cuál es tu estado civil?',
      clarification: 'Determina si puedes plantear declaración conjunta.',
      shortHelp:
          'El estado civil afecta a la opción de tributación conjunta y a algunos mínimos.',
      icon: 'person',
      controlType: 'singleSelect',
      options: [
        'Soltero/a',
        'Casado/a',
        'Pareja de hecho',
        'Viudo/a',
        'Divorciado/a'
      ],
      savesTo: 'declarantA.civilStatus',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 2,
    ),
    QuestionStruct(
      id: 'm01_birth_date',
      module: 'M01',
      questionText: '¿Cuál es tu fecha de nacimiento?',
      clarification:
          'La necesitamos para aplicar los mínimos que dependen de la edad.',
      shortHelp:
          'A partir de los 65 años el mínimo personal aumenta, y hay ventajas fiscales adicionales para mayores de 65 y de 75. Por eso la edad afecta al cálculo.',
      icon: 'person',
      controlType: 'date',
      options: [],
      savesTo: 'declarantA.birthDate',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 3,
    ),
    QuestionStruct(
      id: 'm01_comunidad',
      module: 'M01',
      questionText: '¿En qué comunidad autónoma resides?',
      clarification: 'Dónde has vivido más días este año.',
      shortHelp:
          'La comunidad determina la escala autonómica y las deducciones a las que tienes derecho. Es uno de los datos que más afecta al resultado.',
      icon: 'person',
      controlType: 'dropdown',
      options: [
        'Andalucía',
        'Aragón',
        'Asturias',
        'Canarias',
        'Cantabria',
        'Castilla-La Mancha',
        'Castilla y León',
        'Cataluña',
        'Comunidad Valenciana',
        'Extremadura',
        'Galicia',
        'Islas Baleares',
        'La Rioja',
        'Madrid',
        'Murcia'
      ],
      savesTo: 'familyUnit.autonomousCommunity',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 4,
    ),
    QuestionStruct(
      id: 'm01_conjunta_posible',
      module: 'M01',
      questionText: '¿Quieres que calculemos también la declaración conjunta?',
      clarification:
          'Compararemos individual y conjunta para recomendarte la mejor.',
      shortHelp:
          'Si estás casado, podemos calcular las dos opciones y decirte cuál te conviene. A veces la conjunta ahorra dinero, a veces no.',
      icon: 'person',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.compareJoint',
      required: true,
      conditionField: 'm01_civil_status',
      conditionValue: 'Casado/a',
      order: 5,
    ),

    // ===== M02 - Rendimientos del trabajo =====
    QuestionStruct(
      id: 'm02_intro',
      module: 'M02',
      questionText: 'Ahora vamos con tus ingresos del trabajo',
      clarification: 'Necesitarás los datos de tu certificado de retenciones.',
      shortHelp: '',
      icon: 'briefcase',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 6,
    ),
    QuestionStruct(
      id: 'm02_datos_fiscales',
      module: 'M02',
      questionText: '¿Quieres que rellenemos el cuestionario por ti?',
      clarification:
          'Puedes importar tus datos fiscales de la AEAT o el extracto de tu bróker, y rellenamos por ti lo que contengan. O contestar tú el cuestionario.',
      shortHelp:
          'Los datos fiscales de la AEAT traen tus ingresos, retenciones, Seguridad Social, plan de pensiones, intereses y dividendos. El extracto del bróker aporta además el cálculo de ganancias y pérdidas por venta de valores. Puedes usar los dos: se combinan. Siempre revisarás cada importe antes de que se aplique.',
      icon: 'cloud_download',
      controlType: 'datosFiscalesUpload',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 6.5,
    ),
    QuestionStruct(
      id: 'm02_payer_count',
      module: 'M02',
      questionText: '¿Cuántos pagadores has tenido este año?',
      clarification:
          'Cada empresa o entidad que te pagó cuenta como un pagador.',
      shortHelp:
          'Con dos o más pagadores, el límite de ingresos por debajo del cual no estás obligado a declarar baja de 22.000 a 15.000 EUR.',
      icon: 'briefcase',
      controlType: 'integer',
      options: [],
      savesTo: 'declarantA.payerCount',
      required: true,
      min: 1.0,
      max: 20.0,
      conditionField: '',
      conditionValue: '',
      order: 7,
    ),
    QuestionStruct(
      id: 'm02_gross_income',
      module: 'M02',
      questionText: '¿Cuáles han sido tus retribuciones dinerarias?',
      clarification:
          'El dinero bruto que te pagó tu empresa, antes de descontar IRPF y Seguridad Social.',
      shortHelp:
          'Es la casilla de \'retribuciones dinerarias\' de tu certificado de retenciones (el importe bruto en dinero). No incluyas aquí ni la retribución en especie ni la aportación de la empresa a tu plan de pensiones: te las preguntaremos aparte y las sumaremos nosotros.',
      icon: 'briefcase',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.grossIncome',
      required: true,
      min: 0.0,
      conditionField: '',
      conditionValue: '',
      order: 8,
    ),
    QuestionStruct(
      id: 'm02_especie_si',
      module: 'M02',
      questionText: '¿Tuviste retribuciones en especie?',
      clarification:
          'Seguro médico, tickets restaurante, coche de empresa... Si no tienes o no lo sabes, pon 0.',
      shortHelp:
          'Las retribuciones en especie son pagos no monetarios (seguro de salud, guardería, vehículo...). Aparecen valoradas en tu certificado. Si no tuviste, pon 0.',
      icon: 'briefcase',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 8.5,
    ),
    QuestionStruct(
      id: 'm02_especie',
      module: 'M02',
      questionText: '¿Cuánto valen esas retribuciones en especie?',
      clarification:
          'Seguro médico, tickets restaurante, coche de empresa... Si no tienes o no lo sabes, pon 0.',
      shortHelp:
          'Las retribuciones en especie son pagos no monetarios (seguro de salud, guardería, vehículo...). Aparecen valoradas en tu certificado. Si no tuviste, pon 0.',
      icon: 'briefcase',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.inKindIncome',
      required: false,
      min: 0.0,
      conditionField: 'm02_especie_si',
      conditionValue: 'Sí',
      order: 9,
    ),
    QuestionStruct(
      id: 'm02_withholdings',
      module: 'M02',
      questionText: '¿Cuánto te retuvieron de IRPF?',
      clarification: 'El total de retenciones practicadas.',
      shortHelp:
          'Es el dinero que tu empresa ya adelantó a Hacienda en tu nombre. Se descuenta al final del cálculo.',
      icon: 'briefcase',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.withholdings',
      required: true,
      min: 0.0,
      conditionField: '',
      conditionValue: '',
      order: 10,
    ),
    QuestionStruct(
      id: 'm02_social_security',
      module: 'M02',
      questionText: '¿Cuánto cotizaste a la Seguridad Social?',
      clarification: 'Tu aportación durante el año.',
      shortHelp:
          'Las cotizaciones a la Seguridad Social son un gasto deducible de los rendimientos del trabajo.',
      icon: 'briefcase',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.socialSecurity',
      required: true,
      min: 0.0,
      conditionField: '',
      conditionValue: '',
      order: 11,
    ),
    QuestionStruct(
      id: 'm02_has_union_fee',
      module: 'M02',
      questionText: '¿Pagaste cuota a un sindicato o colegio profesional?',
      clarification: '',
      shortHelp:
          'Las cuotas sindicales y las de colegios profesionales obligatorios son gasto deducible del trabajo.',
      icon: 'briefcase',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasUnionFee',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 12,
    ),
    QuestionStruct(
      id: 'm02_union_fee',
      module: 'M02',
      questionText: '¿Cuánto pagaste de cuota?',
      clarification: 'El total pagado durante el año.',
      shortHelp: '',
      icon: 'briefcase',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.unionFee',
      required: true,
      min: 0.0,
      conditionField: 'm02_has_union_fee',
      conditionValue: 'Sí',
      order: 13,
    ),
    QuestionStruct(
      id: 'm02_foreign_work',
      module: 'M02',
      questionText:
          '¿Has trabajado días en el extranjero para una empresa no española?',
      clarification: 'Puede darte derecho a la exención del artículo 7p.',
      shortHelp:
          'El artículo 7p exime hasta 60.100 EUR de los rendimientos por trabajos realizados en el extranjero, si se cumplen ciertos requisitos.',
      icon: 'briefcase',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasForeignWork',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 14,
    ),
    QuestionStruct(
      id: 'm02_7p_ya_aplicada',
      module: 'M02',
      questionText:
          '¿Tu empresa ya descontó la parte exenta en tu certificado?',
      clarification:
          'Si el salario de tu certificado ya viene con la exención restada, responde Sí.',
      shortHelp:
          'Algunas empresas ya aplican la exención del 7p antes de emitir el certificado: en ese caso, el importe que figura es solo la parte que tributa, y no tienes que hacer nada más. Si no estás seguro, responde No y te preguntaremos el detalle.',
      icon: 'briefcase',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.foreignAlreadyApplied',
      required: true,
      conditionField: 'm02_foreign_work',
      conditionValue: 'Sí',
      order: 15,
    ),
    QuestionStruct(
      id: 'm02_7p_conoce_importe',
      module: 'M02',
      questionText: '¿Conoces el importe exento que te corresponde?',
      clarification:
          'Muchos certificados incluyen la cifra de \'rentas exentas\'. Si la tienes, la usamos directamente.',
      shortHelp:
          'Si tu certificado muestra un importe de rentas exentas por trabajo en el extranjero, es el dato más fiable. Si no lo tienes, lo estimamos a partir de los días que trabajaste fuera.',
      icon: 'briefcase',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.knowsExemptAmount',
      required: true,
      conditionField: 'm02_7p_ya_aplicada',
      conditionValue: 'No',
      order: 16,
    ),
    QuestionStruct(
      id: 'm02_7p_importe',
      module: 'M02',
      questionText: '¿Cuál es el importe exento por trabajo en el extranjero?',
      clarification: 'La cifra de rentas exentas de tu certificado.',
      shortHelp:
          'Es el importe que no tributa por los trabajos realizados en el extranjero (artículo 7p). Máximo legal: 60.100 EUR.',
      icon: 'briefcase',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.exemptAmount7p',
      required: true,
      min: 0.0,
      conditionField: 'm02_7p_conoce_importe',
      conditionValue: 'Sí',
      order: 17,
    ),
    QuestionStruct(
      id: 'm02_foreign_days',
      module: 'M02',
      questionText: '¿Cuántos días trabajaste en el extranjero?',
      clarification: 'Número de días efectivos fuera de España.',
      shortHelp:
          'Estimaremos la parte exenta como proporción de los días fuera sobre el año. Es una aproximación; si tu certificado trae el importe exacto, es preferible usar ese.',
      icon: 'briefcase',
      controlType: 'integer',
      options: [],
      savesTo: 'declarantA.foreignDays',
      required: true,
      min: 1.0,
      max: 366.0,
      conditionField: 'm02_7p_conoce_importe',
      conditionValue: 'No',
      order: 18,
    ),

    // ===== M03 - Hijos y descendientes =====
    QuestionStruct(
      id: 'm03_intro',
      module: 'M03',
      questionText: 'Ahora vamos con tus hijos y descendientes',
      clarification:
          'Los hijos reducen tu impuesto a través del mínimo por descendiente.',
      shortHelp: '',
      icon: 'child_care',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 19,
    ),
    QuestionStruct(
      id: 'm03_tiene_hijos',
      module: 'M03',
      questionText: '¿Tienes hijos o descendientes a tu cargo?',
      clarification:
          'Incluye hijos, nietos u otros descendientes que convivan contigo.',
      shortHelp:
          'Para aplicar el mínimo por descendiente, el hijo debe ser menor de 25 años (o con discapacidad), convivir contigo y no tener rentas altas propias.',
      icon: 'child_care',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.hasChildren',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 20,
    ),
    QuestionStruct(
      id: 'm03_num_hijos',
      module: 'M03',
      questionText: '¿Cuántos hijos o descendientes tienes a tu cargo?',
      clarification: '',
      shortHelp:
          'El importe del mínimo sube con cada hijo: más por el segundo, tercero y siguientes.',
      icon: 'child_care',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.numChildren',
      required: true,
      min: 1.0,
      max: 15.0,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 21,
    ),
    QuestionStruct(
      id: 'm03_hijos_menores_3',
      module: 'M03',
      questionText: '¿Cuántos de ellos son menores de 3 años?',
      clarification: 'A 31 de diciembre del ejercicio.',
      shortHelp:
          'Cada hijo menor de 3 años da un incremento adicional del mínimo por descendiente.',
      icon: 'child_care',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.childrenUnder3',
      required: true,
      min: 0.0,
      max: 15.0,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 22,
    ),
    QuestionStruct(
      id: 'm03_custodia_compartida',
      module: 'M03',
      questionText: '¿Compartes la custodia con el otro progenitor?',
      clarification:
          'Si ambos declarais, el mínimo por hijo se reparte al 50%.',
      shortHelp:
          'Cuando los dos progenitores declaran por separado, el mínimo por descendiente se divide entre ambos.',
      icon: 'child_care',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.sharedCustody',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 23,
    ),
    QuestionStruct(
      id: 'm03_anualidades_alimentos_si',
      module: 'M03',
      questionText:
          '¿Pagas pensión de alimentos a tus hijos por sentencia judicial?',
      clarification:
          'Anualidades por alimentos a los hijos fijadas en un convenio de divorcio o separación aprobado judicialmente.',
      shortHelp:
          'Si pagas una pensión de alimentos a tus hijos establecida por decisión judicial (divorcio o separación), tiene un tratamiento fiscal favorable. Indica el importe anual total. No incluyas la pensión compensatoria al excónyuge (esa es distinta).',
      icon: 'child_care',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 23.5,
    ),
    QuestionStruct(
      id: 'm03_anualidades_alimentos',
      module: 'M03',
      questionText: '¿Cuánto pagas al año por esa pensión de alimentos?',
      clarification:
          'Anualidades por alimentos a los hijos fijadas en un convenio de divorcio o separación aprobado judicialmente.',
      shortHelp:
          'Si pagas una pensión de alimentos a tus hijos establecida por decisión judicial (divorcio o separación), tiene un tratamiento fiscal favorable. Indica el importe anual total. No incluyas la pensión compensatoria al excónyuge (esa es distinta).',
      icon: 'child_care',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.childSupportPayments',
      required: false,
      min: 0.0,
      conditionField: 'm03_anualidades_alimentos_si',
      conditionValue: 'Sí',
      order: 24,
    ),

    // ===== M04 - Discapacidad y ascendientes =====
    QuestionStruct(
      id: 'm04_discapacidad_propia',
      module: 'M04',
      questionText: '¿Tienes reconocido algún grado de discapacidad?',
      clarification: 'Con certificado oficial de discapacidad.',
      shortHelp:
          'Una discapacidad reconocida del 33% o más da derecho a un mínimo adicional que reduce tu impuesto.',
      icon: 'accessible',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasDisability',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 25,
    ),
    QuestionStruct(
      id: 'm04_grado_discapacidad',
      module: 'M04',
      questionText: '¿Cuál es tu grado de discapacidad?',
      clarification: 'El porcentaje que figura en tu certificado.',
      shortHelp:
          'Entre 33% y 65% da un mínimo; a partir del 65% el mínimo es mayor.',
      icon: 'accessible',
      controlType: 'singleSelect',
      options: ['Entre 33% y 64%', '65% o más'],
      savesTo: 'declarantA.disabilityDegree',
      required: true,
      conditionField: 'm04_discapacidad_propia',
      conditionValue: 'Sí',
      order: 26,
    ),
    QuestionStruct(
      id: 'm04_movilidad_reducida',
      module: 'M04',
      questionText:
          '¿Tienes reconocida movilidad reducida o necesitas ayuda de terceros?',
      clarification: '',
      shortHelp: 'Añade un incremento adicional al mínimo por discapacidad.',
      icon: 'accessible',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.reducedMobility',
      required: true,
      conditionField: 'm04_discapacidad_propia',
      conditionValue: 'Sí',
      order: 27,
    ),
    QuestionStruct(
      id: 'm04_ascendientes',
      module: 'M04',
      questionText:
          '¿Convive contigo algún ascendiente mayor de 65 años a tu cargo?',
      clarification: 'Padres o abuelos con rentas bajas que dependan de ti.',
      shortHelp:
          'Un ascendiente mayor de 65 años (o con discapacidad) que conviva contigo y tenga rentas bajas da derecho al mínimo por ascendiente.',
      icon: 'accessible',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.hasAscendants',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 28,
    ),
    QuestionStruct(
      id: 'm04_num_ascendientes',
      module: 'M04',
      questionText: '¿Cuántos ascendientes tienes a tu cargo?',
      clarification: '',
      shortHelp: '',
      icon: 'accessible',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.numAscendants',
      required: true,
      min: 1.0,
      max: 6.0,
      conditionField: 'm04_ascendientes',
      conditionValue: 'Sí',
      order: 29,
    ),
    QuestionStruct(
      id: 'm04_trabajador_activo',
      module: 'M04',
      questionText: '¿Trabajas por cuenta ajena actualmente (en activo)?',
      clarification:
          'Para el incremento de gastos deducibles para trabajadores con discapacidad en activo.',
      shortHelp:
          'Si tienes una discapacidad reconocida y trabajas por cuenta ajena (no es pensión), tienes derecho a un incremento de gastos deducibles de 3.500 € (o 7.750 € si la discapacidad es de grado alto o con movilidad reducida).',
      icon: 'accessible',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.isActiveWorker',
      required: false,
      conditionField: 'm04_discapacidad_propia',
      conditionValue: 'Sí',
      order: 30,
    ),
    QuestionStruct(
      id: 'm04_movilidad_geografica',
      module: 'M04',
      questionText: '¿Cambiaste de municipio este año para aceptar un empleo?',
      clarification: 'Para el incremento de gastos por movilidad geográfica.',
      shortHelp:
          'Si estabas desempleado, te inscribiste en la oficina de empleo y aceptaste un trabajo que te obligó a mudarte a otro municipio, tienes derecho a un incremento de gastos deducibles de 2.000 € (ese año y el siguiente).',
      icon: 'accessible',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.geographicMobility',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 31,
    ),

    // ===== M05 - Intereses y dividendos =====
    QuestionStruct(
      id: 'm05_intro',
      module: 'M05',
      questionText: 'Vamos con tus rendimientos del ahorro',
      clarification: 'Intereses de cuentas y dividendos de acciones o fondos.',
      shortHelp: '',
      icon: 'savings',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 32,
    ),
    QuestionStruct(
      id: 'm05_tiene_intereses',
      module: 'M05',
      questionText: '¿Has recibido intereses de cuentas o depósitos?',
      clarification: '',
      shortHelp:
          'Los intereses de cuentas, depósitos y bonos tributan en la base del ahorro.',
      icon: 'savings',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasInterest',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 33,
    ),
    QuestionStruct(
      id: 'm05_intereses',
      module: 'M05',
      questionText: '¿Cuánto has recibido en intereses este año?',
      clarification: 'Importe íntegro antes de retenciones.',
      shortHelp: '',
      icon: 'savings',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.interest',
      required: true,
      min: 0.0,
      conditionField: 'm05_tiene_intereses',
      conditionValue: 'Sí',
      order: 34,
    ),
    QuestionStruct(
      id: 'm05_tiene_dividendos',
      module: 'M05',
      questionText: '¿Has recibido dividendos de acciones o fondos?',
      clarification: '',
      shortHelp:
          'Los dividendos tributan en la base del ahorro. Si son de fuera de España, puede haber doble imposición (lo veremos más adelante).',
      icon: 'savings',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasDividends',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 35,
    ),
    QuestionStruct(
      id: 'm05_dividendos',
      module: 'M05',
      questionText: '¿Cuánto has recibido en dividendos este año?',
      clarification: 'Importe íntegro antes de retenciones.',
      shortHelp: '',
      icon: 'savings',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.dividends',
      required: true,
      min: 0.0,
      conditionField: 'm05_tiene_dividendos',
      conditionValue: 'Sí',
      order: 36,
    ),
    QuestionStruct(
      id: 'm05_tiene_retenciones_capital',
      module: 'M05',
      questionText: '¿Te retuvieron algo de tus intereses o dividendos?',
      clarification:
          'Los bancos y las empresas retienen un porcentaje al pagarte intereses o dividendos.',
      shortHelp:
          'Esa retención ya se la has adelantado a Hacienda y se descuenta del resultado. Aparece en el certificado de tu banco o de tu bróker, y también en tus datos fiscales de la AEAT. Si no tuviste ni intereses ni dividendos, responde que no.',
      icon: 'savings',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 36.5,
    ),
    QuestionStruct(
      id: 'm05_retenciones_capital',
      module: 'M05',
      questionText: '¿Cuánto te retuvieron de tus intereses y dividendos?',
      clarification:
          'La retención (normalmente el 19%) que te aplicaron sobre intereses y dividendos.',
      shortHelp:
          'Los bancos y las empresas retienen un porcentaje al pagarte intereses o dividendos, y ese dinero ya lo has adelantado a Hacienda. Aparece en tus certificados bancarios o de tu broker. Si no lo sabes, pon 0.',
      icon: 'savings',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.capitalWithholdings',
      required: false,
      min: 0.0,
      conditionField: 'm05_tiene_retenciones_capital',
      conditionValue: 'Sí',
      order: 37,
    ),

    QuestionStruct(
      id: 'm05_gastos_capital_si',
      module: 'M05',
      questionText:
          '¿Has pagado comisiones de administración o custodia de valores?',
      clarification:
          'Lo que te cobra el banco o el bróker por mantener tus valores. Es deducible.',
      shortHelp:
          'Solo son deducibles los gastos de administración y depósito de valores negociables. Las comisiones de compraventa no van aquí: esas forman parte del coste de la operación y se tienen en cuenta al calcular la ganancia. Si no lo sabes, pon 0.',
      icon: 'savings',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 37.25,
    ),
    QuestionStruct(
      id: 'm05_gastos_capital',
      module: 'M05',
      questionText:
          '¿Cuánto pagaste en comisiones de administración y custodia?',
      clarification:
          'Lo que te cobra el banco o el bróker por mantener tus valores. Es deducible.',
      shortHelp:
          'Solo son deducibles los gastos de administración y depósito de valores negociables. Las comisiones de compraventa no van aquí: esas forman parte del coste de la operación y se tienen en cuenta al calcular la ganancia. Si no lo sabes, pon 0.',
      icon: 'savings',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.capitalExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm05_gastos_capital_si',
      conditionValue: 'Sí',
      order: 37.5,
    ),

    // ===== M06 - Acciones y ETFs =====
    QuestionStruct(
      id: 'm06_tiene_ventas',
      module: 'M06',
      questionText: '¿Has vendido acciones o ETFs este año?',
      clarification:
          'Sólo cuenta si has vendido; tener acciones sin vender no tributa.',
      shortHelp:
          'Al vender, la diferencia entre lo que pagaste y lo que recibiste es una ganancia o perdida patrimonial que tributa en la base del ahorro.',
      icon: 'trending_up',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasStockSales',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 38,
    ),
    QuestionStruct(
      id: 'm06_ganancias',
      module: 'M06',
      questionText: '¿Cuál ha sido el total de tus ganancias por ventas?',
      clarification:
          'Suma de las operaciones con beneficio (valor de venta menos compra).',
      shortHelp:
          'Si tu broker te da un informe fiscal, ahi viene el total de ganancias. Más adelante podrás importarlo automáticamente.',
      icon: 'trending_up',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.capitalGains',
      required: true,
      min: 0.0,
      conditionField: 'm06_tiene_ventas',
      conditionValue: 'Sí',
      order: 39,
    ),
    QuestionStruct(
      id: 'm06_perdidas',
      module: 'M06',
      questionText: '¿Cuál ha sido el total de tus perdidas por ventas?',
      clarification: 'Suma de las operaciones con perdida.',
      shortHelp:
          'Las perdidas se restan de las ganancias. Si te quedan perdidas sin compensar, puedes guardarlas para los 4 años siguientes.',
      icon: 'trending_up',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.capitalLosses',
      required: true,
      min: 0.0,
      conditionField: 'm06_tiene_ventas',
      conditionValue: 'Sí',
      order: 40,
    ),
    QuestionStruct(
      id: 'm06_retenciones_ganancias_si',
      module: 'M06',
      questionText: '¿Te retuvieron algo por esas ventas o ganancias?',
      clarification:
          'Retenciones practicadas sobre ganancias patrimoniales (por ejemplo, en la venta de algunos fondos o premios).',
      shortHelp:
          'Algunas ganancias llevan retención (por ejemplo, reembolsos de fondos de inversión o premios). Indica el total retenido por ganancias. Si no hubo retención, pon 0.',
      icon: 'trending_up',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm06_tiene_ventas',
      conditionValue: 'Sí',
      order: 40.5,
    ),
    QuestionStruct(
      id: 'm06_retenciones_ganancias',
      module: 'M06',
      questionText: '¿Cuánto te retuvieron por esas ventas o ganancias?',
      clarification:
          'Retenciones practicadas sobre ganancias patrimoniales (por ejemplo, en la venta de algunos fondos o premios).',
      shortHelp:
          'Algunas ganancias llevan retención (por ejemplo, reembolsos de fondos de inversión o premios). Indica el total retenido por ganancias. Si no hubo retención, pon 0.',
      icon: 'trending_up',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.gainsWithholdings',
      required: false,
      min: 0.0,
      conditionField: 'm06_retenciones_ganancias_si',
      conditionValue: 'Sí',
      order: 41,
    ),
    QuestionStruct(
      id: 'm06_tiene_pendientes',
      module: 'M06',
      questionText: '¿Tienes pérdidas de años anteriores sin compensar?',
      clarification:
          'Pérdidas de ventas de los últimos 4 años que aún no has podido restar.',
      shortHelp:
          'Si en años anteriores (hasta 4 atrás) tuviste pérdidas en ventas que no llegaste a compensar del todo, puedes usarlas ahora para reducir tus ganancias de este año. Lo verás en tus declaraciones anteriores como \'saldos pendientes de compensar\'.',
      icon: 'trending_up',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasPendingLosses',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 42,
    ),
    QuestionStruct(
      id: 'm06_perdidas_pendientes',
      module: 'M06',
      questionText: '¿De qué años son esas pérdidas?',
      clarification:
          'Indica el importe pendiente de cada uno de los cuatro ejercicios anteriores.',
      shortHelp:
          'Las pérdidas patrimoniales que no pudiste compensar se arrastran durante los cuatro ejercicios siguientes, y se compensan empezando por las más antiguas. Por eso hace falta saber de qué año viene cada una y no basta con un total. Las del año más antiguo caducan con esta declaración.',
      icon: 'trending_down',
      controlType: 'perdidasPendientes',
      options: [],
      savesTo: '',
      required: false,
      conditionField: 'm06_tiene_pendientes',
      conditionValue: 'Sí',
      order: 43,
    ),
    QuestionStruct(
      id: 'm06_broker_extranjero',
      module: 'M06',
      questionText: '¿Operas con un broker extranjero (IBKR, DEGIRO...)?',
      clarification: '',
      shortHelp:
          'Si el broker está fuera de España, además podrías tener obligación de declarar el modelo 720 si superas ciertos umbrales (lo veremos más adelante).',
      icon: 'trending_up',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.foreignBroker',
      required: true,
      conditionField: 'm06_tiene_ventas',
      conditionValue: 'Sí',
      order: 44,
    ),
    QuestionStruct(
      id: 'm06_otras_ganancias_si',
      module: 'M06',
      questionText: '¿Has tenido otras ganancias no derivadas de ventas?',
      clarification:
          'Por ejemplo, premios, subvenciones, ayudas públicas o intereses de indemnizaciones.',
      shortHelp:
          'Son ganancias que no vienen de vender algo: premios de lotería no exentos, subvenciones, ayudas públicas (como el Plan MOVES o ayudas al alquiler), o similares. Van a la base general. Si no has tenido, pon 0.',
      icon: 'trending_up',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 44.5,
    ),
    QuestionStruct(
      id: 'm06_otras_ganancias',
      module: 'M06',
      questionText: '¿A cuánto ascienden esas otras ganancias?',
      clarification:
          'Por ejemplo, premios, subvenciones, ayudas públicas o intereses de indemnizaciones.',
      shortHelp:
          'Son ganancias que no vienen de vender algo: premios de lotería no exentos, subvenciones, ayudas públicas (como el Plan MOVES o ayudas al alquiler), o similares. Van a la base general. Si no has tenido, pon 0.',
      icon: 'trending_up',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.otherGains',
      required: false,
      min: 0.0,
      conditionField: 'm06_otras_ganancias_si',
      conditionValue: 'Sí',
      order: 45,
    ),

    // ===== M07 - Fondos de inversion =====
    QuestionStruct(
      id: 'm07_tiene_fondos',
      module: 'M07',
      questionText: '¿Has vendido o reembolsado fondos de inversion este año?',
      clarification:
          'Los traspasos entre fondos NO cuentan; sólo los reembolsos a dinero.',
      shortHelp:
          'Cambiar de un fondo a otro (traspaso) no tributa: sólo tributa cuando reembolsas a dinero. Es una gran ventaja fiscal de los fondos.',
      icon: 'account_balance',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasFundSales',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 46,
    ),
    QuestionStruct(
      id: 'm07_ganancia_fondos',
      module: 'M07',
      questionText: '¿Cuál ha sido la ganancia por los reembolsos?',
      clarification: 'Diferencia entre lo reembolsado y lo invertido.',
      shortHelp:
          'La ganancia tributa en la base del ahorro, igual que las acciones.',
      icon: 'account_balance',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.fundGains',
      required: true,
      min: 0.0,
      conditionField: 'm07_tiene_fondos',
      conditionValue: 'Sí',
      order: 47,
    ),
    QuestionStruct(
      id: 'm07_perdida_fondos_si',
      module: 'M07',
      questionText: '¿Has tenido perdidas en algún reembolso?',
      clarification: '',
      shortHelp: 'Las perdidas se compensan con las ganancias del ahorro.',
      icon: 'account_balance',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm07_tiene_fondos',
      conditionValue: 'Sí',
      order: 47.5,
    ),
    QuestionStruct(
      id: 'm07_perdida_fondos',
      module: 'M07',
      questionText: '¿Cuánto has perdido en esos reembolsos?',
      clarification: '',
      shortHelp: 'Las perdidas se compensan con las ganancias del ahorro.',
      icon: 'account_balance',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.fundLosses',
      required: true,
      min: 0.0,
      conditionField: 'm07_perdida_fondos_si',
      conditionValue: 'Sí',
      order: 48,
    ),

    // ===== M08 - Venta de inmuebles =====
    QuestionStruct(
      id: 'm08_tiene_venta',
      module: 'M08',
      questionText: '¿Has vendido algún inmueble este año?',
      clarification: 'Una vivienda, local, garaje o terreno.',
      shortHelp:
          'La ganancia por vender un inmueble (precio de venta menos precio de compra actualizado) tributa en la base del ahorro. Puede estar exenta en varios casos.',
      icon: 'sell',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasPropertySale',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 49,
    ),
    QuestionStruct(
      id: 'm08_valor_venta',
      module: 'M08',
      questionText: '¿Por cuánto vendiste el inmueble?',
      clarification: 'Precio de venta según la escritura.',
      shortHelp: '',
      icon: 'sell',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.saleValue',
      required: true,
      min: 0.0,
      conditionField: 'm08_tiene_venta',
      conditionValue: 'Sí',
      order: 50,
    ),
    QuestionStruct(
      id: 'm08_valor_compra',
      module: 'M08',
      questionText: '¿Por cuánto lo habias comprado?',
      clarification:
          'Precio de adquisición, más gastos e impuestos de la compra.',
      shortHelp:
          'Puedes sumar al valor de compra los gastos que tuviste (notaría, ITP o IVA, registro) y las mejoras hechas en el inmueble.',
      icon: 'sell',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.purchaseValue',
      required: true,
      min: 0.0,
      conditionField: 'm08_tiene_venta',
      conditionValue: 'Sí',
      order: 51,
    ),
    QuestionStruct(
      id: 'm08_era_habitual',
      module: 'M08',
      questionText: '¿Era tu vivienda habitual?',
      clarification: '',
      shortHelp:
          'Si vendes tu vivienda habitual y reinviertes en otra, la ganancia puede quedar exenta. Y si tienes 65 años o más, está exenta sin necesidad de reinvertir.',
      icon: 'sell',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.saleWasHome',
      required: true,
      conditionField: 'm08_tiene_venta',
      conditionValue: 'Sí',
      order: 52,
    ),
    QuestionStruct(
      id: 'm08_reinversion',
      module: 'M08',
      questionText: '¿Vas a reinvertir en otra vivienda habitual?',
      clarification: 'Tienes dos años para reinvertir.',
      shortHelp:
          'Si reinviertes todo el importe en una nueva vivienda habitual, la ganancia queda totalmente exenta. Si reinviertes sólo una parte, la exención es proporcional.',
      icon: 'sell',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.willReinvest',
      required: true,
      conditionField: 'm08_era_habitual',
      conditionValue: 'Sí',
      order: 53,
    ),
    QuestionStruct(
      id: 'm08_importe_reinvertido',
      module: 'M08',
      questionText: '¿Cuánto vas a reinvertir en la nueva vivienda habitual?',
      clarification:
          'Importe que destinas a comprar tu nueva vivienda habitual (para la exención por reinversión).',
      shortHelp:
          'Si reinviertes todo lo obtenido por la venta en tu nueva vivienda habitual, la ganancia queda totalmente exenta. Si reinviertes solo una parte, la exención es proporcional.',
      icon: 'sell',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.reinvestedAmount',
      required: false,
      min: 0.0,
      conditionField: 'm08_reinversion',
      conditionValue: 'Sí',
      order: 54,
    ),

    // ===== M09 - Inmuebles (alquileres y segundas viviendas) =====
    QuestionStruct(
      id: 'm09_tiene_inmuebles',
      module: 'M09',
      questionText: '¿Tienes inmuebles además de tu vivienda habitual?',
      clarification:
          'Por ejemplo, pisos alquilados o segundas viviendas a tu disposición.',
      shortHelp:
          'Incluye cualquier inmueble que no sea tu vivienda habitual: los que tienes alquilados (generan ingresos) y las segundas viviendas o locales a tu disposición (generan una pequeña imputación de renta). Si solo tienes tu vivienda habitual, responde No.',
      icon: 'home_work',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasProperties',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 55,
    ),
    QuestionStruct(
      id: 'm09_gestionar_inmuebles',
      module: 'M09',
      questionText: 'Tus inmuebles',
      clarification: 'Añade cada uno de tus inmuebles con sus datos.',
      shortHelp:
          'Pulsa el botón para añadir tus inmuebles uno a uno. Para cada uno indicarás si está alquilado o a tu disposición, y sus datos (ingresos, valor catastral, etc.).',
      icon: 'home_work',
      controlType: 'inmuebles',
      options: [],
      savesTo: '',
      required: false,
      conditionField: 'm09_tiene_inmuebles',
      conditionValue: 'Sí',
      order: 56,
    ),

    // ===== M10 - Vivienda e hipoteca =====
    QuestionStruct(
      id: 'm10_hipoteca_anterior_2013',
      module: 'M10',
      questionText:
          '¿Compraste tu vivienda habitual antes de 2013 con hipoteca?',
      clarification:
          'Sólo las hipotecas anteriores a 2013 mantienen la deducción.',
      shortHelp:
          'La deducción por vivienda habitual se eliminó en 2013, pero quien compró antes con hipoteca conserva el derecho a deducir un porcentaje de lo pagado.',
      icon: 'house',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.mortgageBefore2013',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 57,
    ),
    QuestionStruct(
      id: 'm10_pago_hipoteca',
      module: 'M10',
      questionText: '¿Cuánto has pagado de hipoteca este año?',
      clarification: 'Suma de capital más intereses pagados en el año.',
      shortHelp:
          'La deducción es del 15% de lo pagado, con un límite de 9.040 EUR de base.',
      icon: 'house',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.mortgagePayment',
      required: true,
      min: 0.0,
      conditionField: 'm10_hipoteca_anterior_2013',
      conditionValue: 'Sí',
      order: 58,
    ),

    // ===== M11 - Donativos =====
    QuestionStruct(
      id: 'm11_tiene_donativos',
      module: 'M11',
      questionText: '¿Has hecho donativos a ONG o fundaciones?',
      clarification:
          'Donaciones a entidades sin ánimo de lucro acogidas a la ley de mecenazgo.',
      shortHelp:
          'Los donativos a ONG dan una deducción del 80% de los primeros 250 EUR y del 40% del resto. Es de las deducciones más rentables.',
      icon: 'volunteer_activism',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasDonations',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 59,
    ),
    QuestionStruct(
      id: 'm11_importe_donativos',
      module: 'M11',
      questionText: '¿Cuánto has donado en total este año?',
      clarification: 'Suma de todos los donativos.',
      shortHelp: '',
      icon: 'volunteer_activism',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.donations',
      required: true,
      min: 0.0,
      conditionField: 'm11_tiene_donativos',
      conditionValue: 'Sí',
      order: 60,
    ),

    // ===== M12 - Planes de pensiones =====
    QuestionStruct(
      id: 'm12_tiene_plan',
      module: 'M12',
      questionText: '¿Has aportado a un plan de pensiones este año?',
      clarification: 'Planes individuales o de empleo.',
      shortHelp:
          'Las aportaciones a planes de pensiones reducen tu base imponible, con un límite general de 1.500 EUR al año (más si es plan de empleo).',
      icon: 'elderly',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasPensionPlan',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 61,
    ),
    QuestionStruct(
      id: 'm12_aportacion_trabajador',
      module: 'M12',
      questionText: '¿Cuánto aportaste TÚ a tu plan de pensiones?',
      clarification:
          'Solo tu aportación personal, sin contar la de tu empresa.',
      shortHelp:
          'Si es un plan individual que contratas por tu cuenta, es lo que ingresaste durante el año. Si es un plan de empleo, es la parte que descuenta tu empresa de tu nómina como aportación tuya (aparece en tu certificado como \'aportaciones del trabajador\').',
      icon: 'elderly',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.pensionWorker',
      required: true,
      min: 0.0,
      conditionField: 'm12_tiene_plan',
      conditionValue: 'Sí',
      order: 62,
    ),
    QuestionStruct(
      id: 'm12_contribucion_empresa',
      module: 'M12',
      questionText: '¿Cuánto aportó tu EMPRESA a tu plan de pensiones?',
      clarification:
          'La contribución del empleador. Si no tienes plan de empleo, pon 0.',
      shortHelp:
          'Solo aplica si tienes un plan de pensiones de empleo (de empresa). En tu certificado de retenciones aparece como \'contribuciones empresariales a planes de pensiones\'. Si tu plan es individual (lo contrataste tú por tu cuenta), aquí pon 0.',
      icon: 'elderly',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.pensionEmployer',
      required: true,
      min: 0.0,
      conditionField: 'm12_tiene_plan',
      conditionValue: 'Sí',
      order: 63,
    ),

    // ===== M13 - Deducciones autonómicas =====
    QuestionStruct(
      id: 'm13_revisar_deducciones',
      module: 'M13',
      questionText:
          '¿Quieres revisar las deducciones de tu comunidad autónoma?',
      clarification:
          'Cada comunidad tiene deducciones propias (por alquiler, familia, educación, etc.). Te haremos unas preguntas rápidas para ver si te aplican.',
      shortHelp:
          'Las comunidades autónomas ofrecen deducciones que pueden reducir tu factura fiscal: por alquiler de vivienda, por ser familia numerosa o monoparental, por gastos educativos, por inversiones, y más. Si respondes que sí, te haremos unas preguntas para comprobar cuáles te aplican.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.reviewRegionalDeductions',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 64,
    ),
    QuestionStruct(
      id: 'm13_intro',
      module: 'M13',
      questionText: 'Deducciones de tu comunidad autónoma',
      clarification:
          'Ahora revisamos deducciones que puede tener tu comunidad. Responde solo las que apliquen a tu caso.',
      shortHelp:
          'Cada comunidad autónoma tiene sus propias deducciones (por hijos, alquiler, educación...). Te preguntamos por las más habituales; si algo no aplica a tu caso, responde No o deja 0.',
      icon: 'help_outline',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 65,
    ),
    QuestionStruct(
      id: 'm13_hijos_nacidos_si',
      module: 'M13',
      questionText: '¿Ha nacido o adoptado algún hijo este año?',
      clarification:
          'Número de hijos nacidos o adoptados durante el ejercicio.',
      shortHelp:
          'Varias comunidades tienen una deducción por cada hijo nacido o adoptado en el año. En Madrid son 721,70 € por hijo, aplicables los tres primeros años.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 65.5,
    ),
    QuestionStruct(
      id: 'm13_hijos_nacidos',
      module: 'M13',
      questionText: '¿Cuántos hijos han nacido o has adoptado este año?',
      clarification:
          'Número de hijos nacidos o adoptados durante el ejercicio.',
      shortHelp:
          'Varias comunidades tienen una deducción por cada hijo nacido o adoptado en el año. En Madrid son 721,70 € por hijo, aplicables los tres primeros años.',
      icon: 'help_outline',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.childrenBornThisYear',
      required: false,
      min: 0.0,
      conditionField: 'm13_hijos_nacidos_si',
      conditionValue: 'Sí',
      order: 66,
    ),
    QuestionStruct(
      id: 'm13_es_joven_alquiler',
      module: 'M13',
      questionText: '¿Eres menor de 35 años y vives de alquiler?',
      clarification:
          'Para la deducción por arrendamiento de vivienda habitual para jóvenes.',
      shortHelp:
          'Muchas comunidades tienen una deducción para jóvenes que alquilan su vivienda habitual. En Madrid es el 30% de lo pagado, con un máximo de 1.237,20 €.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.isYoungRenter',
      required: false,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 67,
    ),
    QuestionStruct(
      id: 'm13_alquiler_pagado',
      module: 'M13',
      questionText: '¿Cuánto pagaste de alquiler en todo el año?',
      clarification:
          'El total del alquiler de tu vivienda habitual durante el año.',
      shortHelp:
          'Suma todas las mensualidades de alquiler pagadas durante el año por tu vivienda habitual.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.rentPaidAnnual',
      required: false,
      min: 0.0,
      conditionField: 'm13_es_joven_alquiler',
      conditionValue: 'Sí',
      order: 68,
    ),
    QuestionStruct(
      id: 'm13_tiene_gastos_educativos',
      module: 'M13',
      questionText: '¿Has tenido gastos educativos de tus hijos?',
      clarification: 'Escolaridad, enseñanza de idiomas o vestuario escolar.',
      shortHelp:
          'Algunas comunidades deducen un porcentaje de los gastos educativos de los hijos. En Madrid: 15% de escolaridad e idiomas, 5% de vestuario escolar, con límites por hijo.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.hasEducationExpenses',
      required: false,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 69,
    ),
    QuestionStruct(
      id: 'm13_gastos_escolaridad',
      module: 'M13',
      questionText: '¿Cuánto pagaste en escolaridad?',
      clarification:
          'Gastos de escolaridad (colegios privados o concertados en la parte no cubierta).',
      shortHelp:
          'Importe pagado por la escolaridad de tus hijos que dé derecho a deducción según tu comunidad. Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'familyUnit.schoolingExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13_tiene_gastos_educativos',
      conditionValue: 'Sí',
      order: 70,
    ),
    QuestionStruct(
      id: 'm13_gastos_idiomas',
      module: 'M13',
      questionText: '¿Cuánto pagaste en enseñanza de idiomas?',
      clarification: 'Gastos de enseñanza de idiomas de tus hijos.',
      shortHelp:
          'Importe pagado en enseñanza de idiomas de tus hijos. Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'familyUnit.languageExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13_tiene_gastos_educativos',
      conditionValue: 'Sí',
      order: 71,
    ),
    QuestionStruct(
      id: 'm13_gastos_vestuario',
      module: 'M13',
      questionText: '¿Cuánto pagaste en vestuario escolar?',
      clarification: 'Uniformes y vestuario de uso exclusivo escolar.',
      shortHelp:
          'Importe pagado en vestuario de uso exclusivo escolar (uniformes...). Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'familyUnit.schoolClothingExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13_tiene_gastos_educativos',
      conditionValue: 'Sí',
      order: 72,
    ),
    QuestionStruct(
      id: 'm13_cuotas_hogar_si',
      module: 'M13',
      questionText:
          '¿Pagaste a una empleada de hogar por cuidar hijos menores de 3 años?',
      clarification:
          'Cuotas a la Seguridad Social del Sistema Especial de Empleados de Hogar.',
      shortHelp:
          'Si contrataste a alguien (con alta en el Sistema Especial de Empleados de Hogar) para cuidar hijos menores de 3 años, algunas comunidades deducen parte de las cuotas. En Madrid, el 25% (40% familias numerosas), máx. 463,95 €.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 72.5,
    ),
    QuestionStruct(
      id: 'm13_cuotas_hogar',
      module: 'M13',
      questionText: '¿Cuánto pagaste de cuotas de esa empleada de hogar?',
      clarification:
          'Cuotas a la Seguridad Social del Sistema Especial de Empleados de Hogar.',
      shortHelp:
          'Si contrataste a alguien (con alta en el Sistema Especial de Empleados de Hogar) para cuidar hijos menores de 3 años, algunas comunidades deducen parte de las cuotas. En Madrid, el 25% (40% familias numerosas), máx. 463,95 €.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'familyUnit.householdEmployeeQuotas',
      required: false,
      min: 0.0,
      conditionField: 'm13_cuotas_hogar_si',
      conditionValue: 'Sí',
      order: 73,
    ),
    QuestionStruct(
      id: 'm13_familia_numerosa',
      module: 'M13',
      questionText: '¿Eres familia numerosa?',
      clarification: 'Y de qué categoría, si lo eres.',
      shortHelp:
          'Algunas comunidades deducen un porcentaje de la cuota autonómica para familias numerosas. En Madrid: 50% (general) o 100% (especial).',
      icon: 'help_outline',
      controlType: 'singleSelect',
      options: ['No', 'General', 'Especial'],
      savesTo: 'familyUnit.largeFamilyType',
      required: false,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 74,
    ),
    QuestionStruct(
      id: 'm13ar_gastos_guarderia_si',
      module: 'M13',
      questionText: '¿Pagaste guardería de hijos menores de 3 años?',
      clarification:
          'Gastos de custodia en guarderías o centros de educación infantil.',
      shortHelp:
          'Algunas comunidades (como Aragón) deducen un porcentaje de los gastos de guardería de hijos menores de 3 años. En Aragón, el 15%, hasta 250 € por hijo. Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 74.5,
    ),
    QuestionStruct(
      id: 'm13ar_gastos_guarderia',
      module: 'M13',
      questionText: '¿Cuánto pagaste de guardería?',
      clarification:
          'Gastos de custodia en guarderías o centros de educación infantil.',
      shortHelp:
          'Algunas comunidades (como Aragón) deducen un porcentaje de los gastos de guardería de hijos menores de 3 años. En Aragón, el 15%, hasta 250 € por hijo. Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'familyUnit.daycareExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13ar_gastos_guarderia_si',
      conditionValue: 'Sí',
      order: 75,
    ),
    QuestionStruct(
      id: 'm13ar_clases_apoyo_si',
      module: 'M13',
      questionText: '¿Pagaste clases de apoyo o refuerzo educativo?',
      clarification: 'Clases particulares de apoyo o refuerzo para tus hijos.',
      shortHelp:
          'Algunas comunidades (como Aragón) deducen un porcentaje de las clases de apoyo o refuerzo. En Aragón, el 25%, hasta 300 € por hijo. Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 75.5,
    ),
    QuestionStruct(
      id: 'm13ar_clases_apoyo',
      module: 'M13',
      questionText: '¿Cuánto pagaste en clases de apoyo o refuerzo?',
      clarification: 'Clases particulares de apoyo o refuerzo para tus hijos.',
      shortHelp:
          'Algunas comunidades (como Aragón) deducen un porcentaje de las clases de apoyo o refuerzo. En Aragón, el 25%, hasta 300 € por hijo. Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'familyUnit.tutoringExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13ar_clases_apoyo_si',
      conditionValue: 'Sí',
      order: 76,
    ),
    QuestionStruct(
      id: 'm13_inversion_nuevas_si',
      module: 'M13',
      questionText:
          '¿Invertiste en acciones de empresas nuevas o de reciente creación?',
      clarification:
          'Inversión en la constitución o ampliación de capital de entidades nuevas de tu comunidad.',
      shortHelp:
          'Varias comunidades premian invertir en empresas nuevas de su territorio. Madrid deduce el 40% (hasta 9.279 €), Aragón el 20% (hasta 4.000 €). Requiere mantener la inversión un mínimo de años y no superar el 40% del capital.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 76.5,
    ),
    QuestionStruct(
      id: 'm13_inversion_nuevas',
      module: 'M13',
      questionText: '¿Cuánto invertiste en esas empresas?',
      clarification:
          'Inversión en la constitución o ampliación de capital de entidades nuevas de tu comunidad.',
      shortHelp:
          'Varias comunidades premian invertir en empresas nuevas de su territorio. Madrid deduce el 40% (hasta 9.279 €), Aragón el 20% (hasta 4.000 €). Requiere mantener la inversión un mínimo de años y no superar el 40% del capital.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.startupInvestment',
      required: false,
      min: 0.0,
      conditionField: 'm13_inversion_nuevas_si',
      conditionValue: 'Sí',
      order: 77,
    ),
    QuestionStruct(
      id: 'm13_inversion_especial',
      module: 'M13',
      questionText:
          '¿La empresa es una cooperativa, sociedad laboral o de una universidad/centro de investigación?',
      clarification:
          'Estas inversiones tienen un porcentaje de deducción mayor en algunas comunidades.',
      shortHelp:
          'En Madrid, si inviertes en cooperativas, sociedades laborales o entidades creadas por universidades o centros de investigación, la deducción sube al 50% (hasta 12.372 €) en vez del 40%.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.startupInvestmentSpecial',
      required: false,
      conditionField: 'm13_inversion_nuevas',
      conditionValue: '>0',
      order: 78,
    ),
    QuestionStruct(
      id: 'm13_monoparental',
      module: 'M13',
      questionText: '¿Eres una familia monoparental?',
      clarification: 'Un solo progenitor a cargo de los hijos.',
      shortHelp:
          'Algunas comunidades tienen una deducción para familias monoparentales (un solo progenitor con hijos a cargo). En Andalucía son 100 €.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.isSingleParent',
      required: false,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 79,
    ),
    QuestionStruct(
      id: 'm13_es_viudo',
      module: 'M13',
      questionText:
          '¿Has quedado viudo o viuda en los últimos años (2023-2025)?',
      clarification: 'Fallecimiento del cónyuge en los ejercicios recientes.',
      shortHelp:
          'Algunas comunidades (como Cataluña) tienen una deducción para quienes han quedado viudos recientemente. En Cataluña, 150 € (300 € si hay hijos a cargo).',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.isRecentWidow',
      required: false,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 80,
    ),
    QuestionStruct(
      id: 'm13_gastos_rehabilitacion_si',
      module: 'M13',
      questionText:
          '¿Has tenido gastos de rehabilitación de tu vivienda habitual?',
      clarification: 'Obras de rehabilitación de la vivienda habitual.',
      shortHelp:
          'Algunas comunidades (como Cataluña) deducen un porcentaje de los gastos de rehabilitación de la vivienda habitual. En Cataluña, el 1,5% (sobre una base máxima de 9.040 €). Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 80.5,
    ),
    QuestionStruct(
      id: 'm13_gastos_rehabilitacion',
      module: 'M13',
      questionText: '¿Cuánto has gastado en la rehabilitación?',
      clarification: 'Obras de rehabilitación de la vivienda habitual.',
      shortHelp:
          'Algunas comunidades (como Cataluña) deducen un porcentaje de los gastos de rehabilitación de la vivienda habitual. En Cataluña, el 1,5% (sobre una base máxima de 9.040 €). Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.homeRehabExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13_gastos_rehabilitacion_si',
      conditionValue: 'Sí',
      order: 81,
    ),
    QuestionStruct(
      id: 'm13_hijos_3_5_si',
      module: 'M13',
      questionText: '¿Tienes hijos de entre 3 y 5 años?',
      clarification:
          'Para la deducción por conciliación de la vida familiar y laboral.',
      shortHelp:
          'Algunas comunidades (como Valencia) tienen una deducción por conciliación para hijos de 3 a 5 años. En Valencia, 460 € por hijo. Indica cuántos hijos tienes en esa franja de edad.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 81.5,
    ),
    QuestionStruct(
      id: 'm13_hijos_3_5',
      module: 'M13',
      questionText: '¿Cuántos hijos de entre 3 y 5 años tienes?',
      clarification:
          'Para la deducción por conciliación de la vida familiar y laboral.',
      shortHelp:
          'Algunas comunidades (como Valencia) tienen una deducción por conciliación para hijos de 3 a 5 años. En Valencia, 460 € por hijo. Indica cuántos hijos tienes en esa franja de edad.',
      icon: 'help_outline',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.children3to5',
      required: false,
      min: 0.0,
      conditionField: 'm13_hijos_3_5_si',
      conditionValue: 'Sí',
      order: 82,
    ),
    QuestionStruct(
      id: 'm13_material_escolar',
      module: 'M13',
      questionText:
          '¿Cuántos hijos en edad escolar tienes (para material escolar)?',
      clarification:
          'Número de hijos escolarizados que dan derecho a la deducción por material escolar.',
      shortHelp:
          'Algunas comunidades (como Valencia) tienen una deducción fija por hijo por la compra de material escolar. En Valencia, 110 € por hijo escolarizado.',
      icon: 'help_outline',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.schoolMaterialChildren',
      required: false,
      min: 0.0,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 83,
    ),
    QuestionStruct(
      id: 'm13_abonos_culturales_si',
      module: 'M13',
      questionText: '¿Has gastado en abonos o entradas culturales?',
      clarification:
          'Gastos en cultura (teatro, cine, museos, libros...) que dan derecho a deducción.',
      shortHelp:
          'Algunas comunidades (como Valencia) deducen un porcentaje del gasto en cultura. En Valencia, el 21% (si tu base liquidable es inferior a 50.000 €). Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm13_revisar_deducciones',
      conditionValue: 'Sí',
      order: 83.5,
    ),
    QuestionStruct(
      id: 'm13_abonos_culturales',
      module: 'M13',
      questionText: '¿Cuánto has gastado en abonos o entradas culturales?',
      clarification:
          'Gastos en cultura (teatro, cine, museos, libros...) que dan derecho a deducción.',
      shortHelp:
          'Algunas comunidades (como Valencia) deducen un porcentaje del gasto en cultura. En Valencia, el 21% (si tu base liquidable es inferior a 50.000 €). Si no tienes, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.culturalExpenses',
      required: false,
      min: 0.0,
      conditionField: 'm13_abonos_culturales_si',
      conditionValue: 'Sí',
      order: 84,
    ),
    QuestionStruct(
      id: 'm13_adopciones_si',
      module: 'M13',
      questionText: '¿Has tenido gastos de adopción este año?',
      clarification:
          'Solo si has tenido gastos derivados de un proceso de adopción (algunas comunidades los deducen aparte).',
      shortHelp:
          'Algunas comunidades (como Castilla y León) tienen una deducción por los gastos de adopción. En Castilla y León, 784 € (adopción nacional) o 3.625 € (internacional) por hijo adoptado.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm03_tiene_hijos',
      conditionValue: 'Sí',
      order: 84.5,
    ),
    QuestionStruct(
      id: 'm13_adopciones',
      module: 'M13',
      questionText: '¿Cuántas adopciones has tenido este año?',
      clarification:
          'Solo si has tenido gastos derivados de un proceso de adopción (algunas comunidades los deducen aparte).',
      shortHelp:
          'Algunas comunidades (como Castilla y León) tienen una deducción por los gastos de adopción. En Castilla y León, 784 € (adopción nacional) o 3.625 € (internacional) por hijo adoptado.',
      icon: 'help_outline',
      controlType: 'integer',
      options: [],
      savesTo: 'familyUnit.adoptionsThisYear',
      required: false,
      min: 0.0,
      conditionField: 'm13_adopciones_si',
      conditionValue: 'Sí',
      order: 85,
    ),
    QuestionStruct(
      id: 'm13_adopcion_internacional',
      module: 'M13',
      questionText: '¿Alguna de las adopciones fue internacional?',
      clarification:
          'Las adopciones internacionales pueden tener una deducción mayor.',
      shortHelp:
          'En algunas comunidades, la adopción internacional da derecho a una deducción mayor que la nacional. En Castilla y León, 3.625 € frente a 784 €.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: 'familyUnit.internationalAdoption',
      required: false,
      conditionField: 'm13_adopciones',
      conditionValue: '>0',
      order: 86,
    ),

    // ===== M14 - Declaración conjunta (cónyuge) =====
    QuestionStruct(
      id: 'm14_intro',
      module: 'M14',
      questionText: 'Datos de tu cónyuge',
      clarification:
          'Para calcular la declaración conjunta necesitamos los ingresos de tu cónyuge.',
      shortHelp:
          'Para comparar la tributación individual con la conjunta, necesitamos los datos económicos de tu cónyuge. Así calculamos ambas opciones y te decimos cuál te conviene.',
      icon: 'help_outline',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: 'm01_conjunta_posible',
      conditionValue: 'Sí',
      order: 87,
    ),
    QuestionStruct(
      id: 'm14_conyuge_trabajo',
      module: 'M14',
      questionText: '¿Cuánto ganó tu cónyuge por su trabajo (bruto anual)?',
      clarification: 'Retribución íntegra dineraria del trabajo de tu cónyuge.',
      shortHelp:
          'Suma bruta anual que tu cónyuge percibió por su trabajo (antes de retenciones). Lo encuentras en su certificado de retenciones o en su borrador.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantB.workIncome',
      required: false,
      min: 0.0,
      conditionField: 'm01_conjunta_posible',
      conditionValue: 'Sí',
      order: 88,
    ),
    QuestionStruct(
      id: 'm14_conyuge_ss',
      module: 'M14',
      questionText: '¿Cuánto pagó tu cónyuge de Seguridad Social?',
      clarification: 'Cotizaciones a la Seguridad Social de tu cónyuge.',
      shortHelp:
          'Cotizaciones a la Seguridad Social que le descontaron a tu cónyuge durante el año.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantB.socialSecurity',
      required: false,
      min: 0.0,
      conditionField: 'm01_conjunta_posible',
      conditionValue: 'Sí',
      order: 89,
    ),
    QuestionStruct(
      id: 'm14_conyuge_retenciones',
      module: 'M14',
      questionText: '¿Cuánto le retuvieron a tu cónyuge (IRPF)?',
      clarification: 'Retenciones de IRPF practicadas a tu cónyuge.',
      shortHelp:
          'Total de retenciones de IRPF que le practicaron a tu cónyuge durante el año (aparece en su certificado de retenciones).',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantB.withholdings',
      required: false,
      min: 0.0,
      conditionField: 'm01_conjunta_posible',
      conditionValue: 'Sí',
      order: 90,
    ),
    QuestionStruct(
      id: 'm14_conyuge_capital_si',
      module: 'M14',
      questionText: '¿Tu cónyuge tuvo ingresos por intereses o dividendos?',
      clarification:
          'Rendimientos del capital mobiliario de tu cónyuge (aproximado).',
      shortHelp:
          'Si tu cónyuge tuvo intereses de cuentas, dividendos u otros rendimientos del ahorro, indica el total aproximado. Si no tuvo, pon 0.',
      icon: 'help_outline',
      controlType: 'yesNo',
      options: [],
      savesTo: '',
      required: true,
      conditionField: 'm01_conjunta_posible',
      conditionValue: 'Sí',
      order: 90.5,
    ),
    QuestionStruct(
      id: 'm14_conyuge_capital',
      module: 'M14',
      questionText: '¿Cuánto ingresó tu cónyuge por intereses y dividendos?',
      clarification:
          'Rendimientos del capital mobiliario de tu cónyuge (aproximado).',
      shortHelp:
          'Si tu cónyuge tuvo intereses de cuentas, dividendos u otros rendimientos del ahorro, indica el total aproximado. Si no tuvo, pon 0.',
      icon: 'help_outline',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantB.capitalIncome',
      required: false,
      min: 0.0,
      conditionField: 'm14_conyuge_capital_si',
      conditionValue: 'Sí',
      order: 91,
    ),

    // ===== M15 - Fiscalidad internacional =====
    QuestionStruct(
      id: 'm15_rentas_extranjero',
      module: 'M15',
      questionText: '¿Has recibido rentas del extranjero?',
      clarification: 'Dividendos, intereses o ganancias de fuera de España.',
      shortHelp:
          'Si eres residente en España, tributas por tu renta mundial: también por lo que ganas fuera. Pero si ya pagaste impuestos alli, puedes deducirlos para no pagar dos veces.',
      icon: 'public',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasForeignIncome',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 92,
    ),
    QuestionStruct(
      id: 'm15_retencion_origen',
      module: 'M15',
      questionText: '¿Te retuvieron impuestos en el país de origen?',
      clarification:
          'Por ejemplo, la retención sobre dividendos de acciones extranjeras.',
      shortHelp:
          'España te deja deducir lo que ya pagaste fuera, hasta el límite que marca el convenio con ese país. Si te retuvieron de más, ese exceso se reclama al país de origen, no aquí.',
      icon: 'public',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.foreignWithholding',
      required: true,
      conditionField: 'm15_rentas_extranjero',
      conditionValue: 'Sí',
      order: 93,
    ),
    QuestionStruct(
      id: 'm15_importe_retenido',
      module: 'M15',
      questionText: '¿Cuánto te retuvieron en el extranjero?',
      clarification: 'Total de impuestos pagados fuera.',
      shortHelp: '',
      icon: 'public',
      controlType: 'amount',
      options: [],
      savesTo: 'declarantA.foreignTaxPaid',
      required: true,
      min: 0.0,
      conditionField: 'm15_retencion_origen',
      conditionValue: 'Sí',
      order: 94,
    ),
    QuestionStruct(
      id: 'm15_pais',
      module: 'M15',
      questionText: '¿De qué país proceden principalmente esas rentas?',
      clarification: 'Para aplicar el convenio correcto.',
      shortHelp:
          'Cada país tiene un convenio con España que fija el límite de lo que se puede deducir. Los países más comunes ya estan cargados.',
      icon: 'public',
      controlType: 'dropdown',
      options: [
        'Estados Unidos',
        'Reino Unido',
        'Alemania',
        'Francia',
        'Irlanda',
        'Países Bajos',
        'Suiza',
        'Otro'
      ],
      savesTo: 'declarantA.foreignCountry',
      required: true,
      conditionField: 'm15_retencion_origen',
      conditionValue: 'Sí',
      order: 95,
    ),
    QuestionStruct(
      id: 'm15_bienes_extranjero',
      module: 'M15',
      questionText: '¿Tienes cuentas, valores o inmuebles en el extranjero?',
      clarification:
          'Cuentas bancarias, carteras en brokers extranjeros o propiedades fuera.',
      shortHelp:
          'Si el valor de alguna de estas categorías supera 50.000 EUR, podrías tener obligación de presentar el modelo 720 (declaración informativa). Lo comprobamos ahora.',
      icon: 'public',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.hasForeignAssets',
      required: true,
      conditionField: '',
      conditionValue: '',
      order: 96,
    ),

    // ===== M16 - Modelo 720 (bienes en el extranjero) =====
    QuestionStruct(
      id: 'm16_intro',
      module: 'M16',
      questionText: 'Vamos a comprobar si debes presentar el modelo 720',
      clarification:
          'Es una declaración informativa, no paga impuestos. Sólo informa.',
      shortHelp:
          'El 720 tiene tres categorías independientes (cuentas, valores, inmuebles), cada una con su propio umbral de 50.000 EUR. Se comprueban por separado.',
      icon: 'flight',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: 'm15_bienes_extranjero',
      conditionValue: 'Sí',
      order: 97,
    ),
    QuestionStruct(
      id: 'm16_cuentas',
      module: 'M16',
      questionText:
          '¿El saldo de tus cuentas en el extranjero supera 50.000 EUR?',
      clarification: 'Sumando todas tus cuentas bancarias fuera de España.',
      shortHelp:
          'Se mira tanto el saldo a 31 de diciembre como el saldo medio del último trimestre. Si cualquiera supera 50.000, hay que declarar esta categoría.',
      icon: 'flight',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.form720Accounts',
      required: true,
      conditionField: 'm15_bienes_extranjero',
      conditionValue: 'Sí',
      order: 98,
    ),
    QuestionStruct(
      id: 'm16_valores',
      module: 'M16',
      questionText:
          '¿El valor de tus acciones y fondos en el extranjero supera 50.000 EUR?',
      clarification: 'Carteras en brokers extranjeros (IBKR, DEGIRO...).',
      shortHelp:
          'Es una categoría independiente de las cuentas. Puedes tener que declarar valores aunque tus cuentas no lleguen al umbral.',
      icon: 'flight',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.form720Securities',
      required: true,
      conditionField: 'm15_bienes_extranjero',
      conditionValue: 'Sí',
      order: 99,
    ),
    QuestionStruct(
      id: 'm16_inmuebles',
      module: 'M16',
      questionText:
          '¿El valor de tus inmuebles en el extranjero supera 50.000 EUR?',
      clarification: 'Propiedades fuera de España.',
      shortHelp:
          'Tercera categoría independiente. Se valora por el precio de adquisición.',
      icon: 'flight',
      controlType: 'yesNo',
      options: [],
      savesTo: 'declarantA.form720RealEstate',
      required: true,
      conditionField: 'm15_bienes_extranjero',
      conditionValue: 'Sí',
      order: 100,
    ),

    // ===== MZZ - Ultimos detalles =====
    QuestionStruct(
      id: 'mzz_intro',
      module: 'MZZ',
      questionText:
          'Ya casi estamos. Ultimos detalles para afinar tu declaración',
      clarification: 'Algunas deducciones dependen de tu comunidad autónoma.',
      shortHelp: '',
      icon: 'checklist',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 101,
    ),
    QuestionStruct(
      id: 'mzz_final',
      module: 'MZZ',
      questionText: 'Hemos terminado de recopilar tus datos',
      clarification:
          'Ahora calcularemos tu declaración y te mostraremos el resultado.',
      shortHelp: '',
      icon: 'checklist',
      controlType: 'info',
      options: [],
      savesTo: '',
      required: false,
      conditionField: '',
      conditionValue: '',
      order: 102,
    ),
  ];
}
